// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1.Data;

#nullable disable

namespace WebApp1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241029041102_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4,
                            Name = "MicroPhone1",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 9,
                            Name = "MicroPhone2",
                            Price = 83.0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2,
                            Name = "MicroPhone3",
                            Price = 71.0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2,
                            Name = "MicroPhone4",
                            Price = 74.0
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2,
                            Name = "MicroPhone5",
                            Price = 28.0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 8,
                            Name = "MicroPhone6",
                            Price = 42.0
                        },
                        new
                        {
                            Id = 7,
                            Amount = 9,
                            Name = "MicroPhone7",
                            Price = 12.0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 6,
                            Name = "MicroPhone8",
                            Price = 85.0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 8,
                            Name = "MicroPhone9",
                            Price = 74.0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 8,
                            Name = "MicroPhone10",
                            Price = 90.0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 8,
                            Name = "MicroPhone11",
                            Price = 61.0
                        },
                        new
                        {
                            Id = 12,
                            Amount = 4,
                            Name = "MicroPhone12",
                            Price = 56.0
                        },
                        new
                        {
                            Id = 13,
                            Amount = 9,
                            Name = "MicroPhone13",
                            Price = 89.0
                        },
                        new
                        {
                            Id = 14,
                            Amount = 8,
                            Name = "MicroPhone14",
                            Price = 67.0
                        },
                        new
                        {
                            Id = 15,
                            Amount = 8,
                            Name = "MicroPhone15",
                            Price = 17.0
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1,
                            Name = "MicroPhone16",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 17,
                            Amount = 8,
                            Name = "MicroPhone17",
                            Price = 43.0
                        },
                        new
                        {
                            Id = 18,
                            Amount = 9,
                            Name = "MicroPhone18",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 19,
                            Amount = 9,
                            Name = "MicroPhone19",
                            Price = 13.0
                        },
                        new
                        {
                            Id = 20,
                            Amount = 7,
                            Name = "MicroPhone20",
                            Price = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
